-- MON TERRA RESIDENCE — database schema
-- Run this once in Supabase > SQL Editor > New query.

create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  city text not null,
  address text,
  handover_quarter text,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.layout_types (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  code text not null,
  style_name text not null,
  rooms integer not null check (rooms between 1 and 10),
  area numeric(8,2) not null check (area > 0),
  base_price numeric(12,2) not null check (base_price >= 0),
  floorplan_url text not null,
  cutaway_url text not null,
  tour_rooms jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  published boolean not null default true,
  unique(project_id, code)
);

create table if not exists public.apartments (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  layout_type_id uuid not null references public.layout_types(id) on delete restrict,
  unit_number text not null,
  slug text unique not null,
  building text not null,
  floor integer not null check (floor >= 0),
  rooms integer not null check (rooms between 1 and 10),
  area numeric(8,2) not null check (area > 0),
  balcony_type text not null default 'balcony' check (balcony_type in ('balcony','terrace','garden','none')),
  balcony_area numeric(8,2) not null default 0 check (balcony_area >= 0),
  exposure text,
  ceiling_height numeric(4,2) not null default 2.70,
  status text not null default 'available' check (status in ('available','reserved','sold')),
  price numeric(12,2) not null check (price >= 0),
  price_per_sqm numeric(12,2) generated always as (
    case when area > 0 then round(price / area, 2) else 0 end
  ) stored,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, unit_number)
);

create index if not exists apartments_project_idx on public.apartments(project_id);
create index if not exists apartments_status_idx on public.apartments(status);
create index if not exists apartments_filter_idx on public.apartments(rooms, floor, area, price);

create table if not exists public.addons (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  slug text not null,
  name text not null,
  description text,
  category text not null check (category in ('parking','storage','finish','smart')),
  selection_group text not null,
  price_type text not null check (price_type in ('fixed','per_sqm')),
  price_value numeric(12,2) not null check (price_value >= 0),
  sort_order integer not null default 0,
  active boolean not null default true,
  unique(project_id, slug)
);

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete set null,
  apartment_id uuid references public.apartments(id) on delete set null,
  name text not null,
  phone text not null,
  email text not null,
  message text,
  selected_addons jsonb not null default '[]'::jsonb,
  base_price numeric(12,2) not null default 0,
  addons_total numeric(12,2) not null default 0,
  total_price numeric(12,2) not null default 0,
  source text not null default 'website',
  status text not null default 'new' check (status in ('new','contacted','meeting','won','lost')),
  assigned_to uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists leads_created_idx on public.leads(created_at desc);
create index if not exists leads_status_idx on public.leads(status);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  apartment_id uuid not null references public.apartments(id) on delete cascade,
  old_price numeric(12,2),
  new_price numeric(12,2) not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists price_history_apartment_idx on public.price_history(apartment_id, changed_at desc);

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'admin' check (role in ('admin','sales')),
  created_at timestamptz not null default now()
);

create table if not exists public.construction_updates (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null,
  body text,
  progress integer not null default 0 check (progress between 0 and 100),
  image_url text,
  published boolean not null default true,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- Generic updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists apartments_set_updated_at on public.apartments;
create trigger apartments_set_updated_at before update on public.apartments
for each row execute function public.set_updated_at();

drop trigger if exists leads_set_updated_at on public.leads;
create trigger leads_set_updated_at before update on public.leads
for each row execute function public.set_updated_at();

-- Fill project_id automatically from selected apartment when a lead is created.
create or replace function public.set_lead_project_from_apartment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.project_id is null and new.apartment_id is not null then
    select a.project_id into new.project_id
    from public.apartments a
    where a.id = new.apartment_id;
  end if;
  return new;
end;
$$;

drop trigger if exists leads_set_project on public.leads;
create trigger leads_set_project
before insert on public.leads
for each row execute function public.set_lead_project_from_apartment();

-- Automatic price history when an admin changes apartment price.
create or replace function public.log_apartment_price_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.price is distinct from new.price then
    insert into public.price_history(apartment_id, old_price, new_price, changed_by)
    values (new.id, old.price, new.price, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists apartments_price_history on public.apartments;
create trigger apartments_price_history
after update of price on public.apartments
for each row execute function public.log_apartment_price_change();

-- Admin helper used by RLS policies.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_profiles p
    where p.user_id = auth.uid()
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

-- RLS
alter table public.projects enable row level security;
alter table public.layout_types enable row level security;
alter table public.apartments enable row level security;
alter table public.addons enable row level security;
alter table public.leads enable row level security;
alter table public.price_history enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.construction_updates enable row level security;

-- Clean policy recreation
DROP POLICY IF EXISTS "public read projects" ON public.projects;
CREATE POLICY "public read projects" ON public.projects FOR SELECT USING (published = true OR public.is_admin());
DROP POLICY IF EXISTS "admin manage projects" ON public.projects;
CREATE POLICY "admin manage projects" ON public.projects FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "public read layouts" ON public.layout_types;
CREATE POLICY "public read layouts" ON public.layout_types FOR SELECT USING (published = true OR public.is_admin());
DROP POLICY IF EXISTS "admin manage layouts" ON public.layout_types;
CREATE POLICY "admin manage layouts" ON public.layout_types FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "public read apartments" ON public.apartments;
CREATE POLICY "public read apartments" ON public.apartments FOR SELECT USING (published = true OR public.is_admin());
DROP POLICY IF EXISTS "admin manage apartments" ON public.apartments;
CREATE POLICY "admin manage apartments" ON public.apartments FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "public read addons" ON public.addons;
CREATE POLICY "public read addons" ON public.addons FOR SELECT USING (active = true OR public.is_admin());
DROP POLICY IF EXISTS "admin manage addons" ON public.addons;
CREATE POLICY "admin manage addons" ON public.addons FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "public create leads" ON public.leads;
CREATE POLICY "public create leads" ON public.leads FOR INSERT TO anon, authenticated
WITH CHECK (status = 'new' AND source = 'website');
DROP POLICY IF EXISTS "admin read leads" ON public.leads;
CREATE POLICY "admin read leads" ON public.leads FOR SELECT TO authenticated USING (public.is_admin());
DROP POLICY IF EXISTS "admin update leads" ON public.leads;
CREATE POLICY "admin update leads" ON public.leads FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "admin delete leads" ON public.leads;
CREATE POLICY "admin delete leads" ON public.leads FOR DELETE TO authenticated USING (public.is_admin());

DROP POLICY IF EXISTS "public read price history" ON public.price_history;
CREATE POLICY "public read price history" ON public.price_history FOR SELECT USING (true);
DROP POLICY IF EXISTS "admin manage price history" ON public.price_history;
CREATE POLICY "admin manage price history" ON public.price_history FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "user read own admin profile" ON public.admin_profiles;
CREATE POLICY "user read own admin profile" ON public.admin_profiles FOR SELECT TO authenticated USING (user_id = auth.uid());
DROP POLICY IF EXISTS "user update own admin profile" ON public.admin_profiles;
CREATE POLICY "user update own admin profile" ON public.admin_profiles FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "public read construction updates" ON public.construction_updates;
CREATE POLICY "public read construction updates" ON public.construction_updates FOR SELECT USING (published = true OR public.is_admin());
DROP POLICY IF EXISTS "admin manage construction updates" ON public.construction_updates;
CREATE POLICY "admin manage construction updates" ON public.construction_updates FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
